<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading<?= $this->id ?>">
        <h4 class="panel-title">
            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapse<?= $this->id ?>"
               aria-expanded="true" aria-controls="collapse<?= $this->id ?>">
                <?= $this->title ?>
            </a>
        </h4>
    </div>
    <div id="collapse<?= $this->id ?>" class="panel-collapse collapse" role="tabpanel"
         aria-labelledby="heading<?= $this->id ?>">
        <div class="panel-body">
            <?= $this->description; ?>


        </div>
    </div>
    <hr>
</div>