<?= $this->partial('admin/partial/nav.phtml'); ?>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Vídeo</h3>
        </div>
        <div class="panel-body">
            <?= $this->form(null, null)->openTag($this->form->prepare()); ?>
            <?= $this->formRow($this->form->get('title')); ?>
            <?= $this->formRow($this->form->get('description')); ?>
            <?= $this->formRow($this->form->get('embed')); ?>
            <?= $this->formRow($this->form->get('active')); ?>
            <?= $this->render('admin/buttons.phtml'); ?>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>