<?= $this->partial('admin/partial/nav.phtml'); ?>

<div class="container">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title pull-left">Assinaturas</h3>
            <a href="<?= $this->url('admin/signature/add', ['customerId' => $this->customerId, 'modal' => $this->modal]); ?>"
               class="pull-right fancybox"
                <?= ($this->modal) ? 'data-fancybox-type="ajax"' : '' ?>>Adicionar Assinatura</a>
            <div class="clearfix"></div>
        </div>
        <table class="table table-striped table-hover table-condensed">
            <thead>
            <tr>
                <th width="100">#</th>
                <th>Cliente</th>
                <th>Plano</th>
                <th>Início</th>
                <th>Término</th>
                <th width="100">Ativo</th>
                <th width="200"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->rows as $row) { ?>
                <tr>
                    <td>#<?= $this->escapeHtml($row['id']); ?></td>
                    <td><?= $this->escapeHtml($row['customer_name']); ?></td>
                    <td><?= $this->escapeHtml($row['plan_name']); ?></td>
                    <td><?= $this->DateFormatHelper($this->escapeHtml($row['date_initial'])); ?></td>
                    <td><?= $this->DateFormatHelper($this->escapeHtml($row['date_end'])); ?></td>
                    <td><?= $this->StatusActiveHelper($this->escapeHtml($row['active'])); ?></td>
                    <td>
                        <a href="<?= $this->url('admin/signature/edit', ['id' => $row['id']]); ?>"
                           class="btn btn-link">Alterar</a>
                        <?php if (!$this->modal) { ?>
                            <a href="<?= $this->url('admin/physical-evaluation/list', ['signatureId' => $row['id'], 'modal' => true]); ?>"
                               class="btn btn-link fancybox"
                               data-fancybox-type="ajax">Medições</a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>

            <?php
            if (!count($this->rows)) {
                echo '<tr>';
                echo '<td colspan="10">';
                echo 'Nenhum registro disponível.';
                echo '</td>';
                echo '</tr>';
            }
            ?>
            </tbody>
        </table>
    </div>
</div>