<div class="spacing30px"></div>
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li><a href="<?= $this->url('admin/plan'); ?>">Planos</a></li>
                <li><a href="<?= $this->url('admin/customer'); ?>">Clientes</a></li>
                <li><a href="<?= $this->url('admin/signature'); ?>">Assinaturas</a></li>
                <li><a href="<?= $this->url('admin/movie'); ?>">Vídeos</a></li>
                <li><a href="<?= $this->url('admin/training'); ?>">Treinos</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?= $this->url('admin/auth/logout') ?>">Sair</a></li>
            </ul>
        </div>
    </nav>
</div>