<?= $this->doctype() ?>

<html lang="pt-Br">
    <?= $this->render('partial/head.phtml') ?>
    <body>
        <header>
            <?= $this->render('partial/nav.phtml') ?>
            <?= $this->partial('partial/show-message.phtml', ['flashMessages' => $this->flashMessages]); ?>
        </header>
        <?= $this->content ?>
        <?= $this->render('partial/scripts.phtml') ?>
		<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-97686237-1', 'auto');
  ga('send', 'pageview');

</script>
    </body>
</html>
