<section class="index" id="about-us">
    <div class="container">
        <h1>SOBRE NÓS</h1>
        <h2>Saiba como estamos revolucionando o mundo dos treinos</h2>

        <div class="spacing15px"></div>

        <h3>Flexibilidade, equilíbrio e força</h3>

        <div class="spacing15px"></div>

        <p class="description">
            O Studio Pro Treino é o local certo para quem procura o treinamento funcional.
            Saia da rotina dos treinos monótonos de academia, o treinamento funcional baseia-se nos movimentos naturais do ser humano, como pular, correr, puxar, agachar, girar e empurrar. O praticante ganha força, equilíbrio, flexibilidade, condicionamento, resistência e agilidade.
            Ele tira a pessoa dos movimentos mecânicos e eixos definidos ou isolados, como acontece na musculação. Por isso, virou uma alternativa para quem estava cansado dos exercícios mais tradicionais na academia.
            Oferecemos serviço personalizado, baseado em seu perfil e objetivos. Venha conhecer o <b>Studio Pro Treino</b>, a primeira aula é grátis!
        </p>
    </div>
</section>