<div class="container">
    <section class="index" id="how-it-works">
        <h1>COMO FUNCIONA</h1>
        <h2>Entenda nosso método de trabalho</h2>

        <div class="spacing30px"></div>

        <p class="description">
            Somos especializados em treinamento funcional, essa nova modalidade que está trazendo resultados cada vez
            mais satisfatórios em todo o mundo.
            O treinamento funcional pode ser feito por qualquer tipo de pessoa, pois é baseado nos movimentos naturais
            do ser humano como pular, correr, puxar, agachar, girar e empurrar.
            Oferecemos dois tipos de serviço:
        </p>
        <p class="description">
            1. Treinamento no studio <br>
            O aluno é acompanhado de perto, com treinos personalizados e resultado eficaz. O studio
            oferece uma gama de aparelhos e instrumentos para a prática do treinamento funcional. Aqui o aluno conta com
            amplo espaço, ar condicionado e treinador capacitado.
        </p>
        <p class="description">
            2. Acompanhamento de Treino <br>
            Para quem exige um acompanhamento profissional mas prefere treinar em sua academia, este é o plano perfeito.
            Elaboramos avaliações e treinos personalizados, baseados em seu perfil e objetivos. O acompanhamento ocorre
            mensalmente, sendo que o aluno pode tirar dúvidas no momento que precisar.
        </p>
    </section>
</div>