<section class="index" id="home">
    <div class="container">
        <h1>Já conhece o <br>
            treinamento <br>
            funcional?</h1>
        <a href="#" data-anchor="#service" class="btn btn-block btn-service">
            Conheça nossos serviços
        </a>
    </div>
</section>

<?= $this->render('service.phtml'); ?>
<?= $this->render('how-it-works.phtml'); ?>
<?= $this->render('plans.phtml'); ?>
<?= $this->render('about-us.phtml'); ?>
<?= $this->render('contact.phtml'); ?>