<section class="index" id="service" style="position: relative; padding-bottom: 60px;">
    <div class="bg-service"></div>
    <div class="container">
        <h1>SERVIÇOS</h1>
        <h2>Em que podemos te ajudar?</h2>

        <div class="hidden-xs">
            <div class="spacing30px"></div>
            <div class="spacing30px"></div>
        </div>

        <div id="carousel" class="carousel slide" data-ride="carousel" data-interval="15000">
            <div class="carousel-inner" role="listbox">
                <div class="item active" data-slide-number="0">
                    <h3 class="description">Hipertrofia</h3>
                    <p class="description">
                        O treinamento funcional visa o desenvolvimento de uma maneira muito mais generalizada. Nesta
                        modalidade, “o corpo é tratado como um todo”. É trabalhado muitas atividades motoras como:
                        andar, correr, saltar, agachar, levantar, empurrar e puxar.
                        Esse método de treinamento age integrando e interagindo suas estruturas corporais aprimorando a
                        ativação das unidades motoras dos seus músculos.
                    </p>
                </div>
                <div class="item" data-slide-number="1">
                    <h3 class="description">Condicionamento físico</h3>
                    <p class="description">
                        Fala-se muito de um treinamento diferente e criativo no universo fitness. Ele chama-se
                        Treinamento Funcional. Promove ganho de resistência, força, flexibilidade, equilíbrio, entre
                        outros, também condiciona e emagrece.
                        O Treinamento Funcional está diretamente ligado a sua rotina diária de atividades, seja ela
                        social ou fitness. Realizamos muitas atividades motoras como: andar, correr, saltar, agachar,
                        levantar, empurrar e puxar.
                        Venha experimentar.
                    </p>
                </div>
                <div class="item" data-slide-number="2">
                    <h3 class="description">Emagrecimento</h3>
                    <p class="description">
                        Fala-se muito de um treinamento diferente e criativo no universo fitness. Ele chama-se
                        Treinamento Funcional. Promove ganho de resistência, força, flexibilidade, equilíbrio, entre
                        outros, também condiciona e emagrece.
                        O Treinamento Funcional está diretamente ligado a sua rotina diária de atividades, seja ela
                        social ou fitness. Realizamos muitas atividades motoras como: andar, correr, saltar, agachar,
                        levantar, empurrar e puxar.
                        Venha experimentar.
                        Emagrecimento
                        Muitas pessoas sentem-se desmotivadas em treinar em academias pela monotonia dos treinos. O
                        exercício funcional chegou para quebrar com essa rotina desmotivadora.
                        Os exercícios funcionais são compostos pela realização de diversos movimentos, e vale ressaltar
                        que o objetivo central é atingir os objetivos particulares de cada um.
                        Combinando movimentos direcionados para um grupo de músculos, o treino funcional trabalha o
                        corpo como um todo. Dessa forma, esses treinos podem auxiliar no melhor condicionamento do corpo
                        e de sua coordenação motora. Os benefícios não só se limitam ao seu corpo, mas também à sua
                        mente.
                    </p>
                </div>
                <div class="item" data-slide-number="3">
                    <h3 class="description">Reabilitação</h3>
                    <p class="description">
                        O treinamento funcional insere atividades rotineiras do ser humano no treino em um contexto
                        variado de métodos, tem como objetivo tornar o corpo mais inteligente, produzindo movimentos
                        precisos e eficientes. O Método baseia-se nos movimentos naturais do ser humano, como correr,
                        saltar, girar, puxar, empurrar e agachar.
                        Utilizado na reabilitação, o treinamento funcional condiciona o paciente no retorno as suas
                        atividades de vida diária, sendo eficiente e primordial no que se refere à melhoria da qualidade
                        de vida da população.
                    </p>
                </div>
            </div>

            <!-- Controls -->
            <a class="left carousel-control" href="#carousel" role="button" data-slide="prev">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
                <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel" role="button" data-slide="next">
                <i class="fa fa-angle-right" aria-hidden="true"></i>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
    <ol class="carousel-indicators">
        <li data-target="#carousel" id="carousel-selector-0" data-slide-to="0" class="active"></li>
        <li data-target="#carousel" id="carousel-selector-1" data-slide-to="1"></li>
        <li data-target="#carousel" id="carousel-selector-2" data-slide-to="2"></li>
        <li data-target="#carousel" id="carousel-selector-3" data-slide-to="3"></li>
    </ol>
    <div style="display:none">
        <img src="/img/banner-servico-0.jpg" alt="Hipertrofia">
        <img src="/img/banner-servico-1.jpg" alt="Condicionamento físico">
        <img src="/img/banner-servico-2.jpg" alt="Emagrecimento">
        <img src="/img/banner-servico-3.jpg" alt="Reabilitação">
    </div>
</section>
