<footer class="main-footer">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-5 col-md-5 col-lg-5 hidden-xs">
                <h3>Pro Treino</h3>
                <ul class="nav navbar-nav nav-footer">
                    <li><a href="#" data-anchor="#service">Serviço</a></li>
                    <li><a href="#" data-anchor="#about-us">Sobre Nós</a></li>
                    <li><a href="#" data-anchor="#how-it-works">Como funciona</a></li>
                    <li><a href="#" data-anchor="#plans">Planos</a></li>
                    <li><a href="#" data-anchor="#contact">Contato</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-7 col-md-7 col-lg-7">
                <h3>Rede Social</h3>
                <ul class="nav navbar-nav social">
                    <li>
                        <a href="https://www.facebook.com/romariomessiastreinador/?fref=ts" target="_blank"><i class="fa fa-facebook-official" aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="https://www.instagram.com/studio_protreino/?r=sun1" target="_blank"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                    </li>
                    <li>
                        <a href="https://www.youtube.com/user/romariomessias" target="_blank"><i class="fa fa-youtube-play" aria-hidden="true"></i></a>
                    </li>
<!--                    <li>-->
<!--                        <a href="#"><i class="fa fa-whatsapp" aria-hidden="true"></i></a>-->
<!--                    </li>-->
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="spacing30px visible-xs clearfix"></div>
            </div>
            <div class="col-xs-12 col-sm-6 col-sm-offset-3">
                <address class="text-center" style="margin-top: 35px">
                    Rua Sperendio Cabrini, 191 - Maria Izabel | 17516-300 - Marília SP | 14 99685-8103
                </address>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-4 col-lg-3">
                <a href="http://getaweb.com.br" target="_blank" class="text-right" style="color: white;display: block;">
                    <small>Desenvolvido com carinho por:</small>
                    <br>
                    <img src="http://getaweb.com.br/images/logo.png" alt="" title="GetAWeb" height="23">
                </a>
            </div>
        </div>
    </div>
</footer>