<head>
    <meta charset="utf-8">
    <?= $this->headTitle('PRO TREINO')->setSeparator(' - ')->setAutoEscape(true) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('css/layout.css?p=' . time()))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ->prependStylesheet($this->basePath('js/icheck/skins/square/orange.css'))
        ->prependStylesheet($this->basePath('js/toastr/toastr.min.css'))
        ->prependStylesheet($this->basePath('js/fancy-box/jquery.fancybox.css'))
        ->prependStylesheet($this->basePath('js/select2/css/select2.min.css'))
        ->prependStylesheet($this->basePath('js/daterangepicker/daterangepicker-bs3.css'))
        ->prependStylesheet('https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700')
        ->prependStylesheet('https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css')
    ?>
</head>