<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?= $this->url('home') ?>">
                <img src="<?= $this->basePath('img/logo-pro-treino.png') ?>" height="28"
                     title="Clique para acessar a página inicial"
                     alt="Clique para acessar a página inicial"
                     class="img-responsive" style="    margin-top: 4px;"/>
            </a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <?php if ($this->isLogged) { ?>
                <div style="display: none;">
                    <?php } ?>
                    <li><a href="#" data-anchor="#service">Serviço</a></li>
                    <li><a href="#" data-anchor="#how-it-works">Como funciona</a></li>
                    <li><a href="#" data-anchor="#plans">Planos</a></li>
                    <li><a href="#" data-anchor="#about-us">Sobre Nós</a></li>
                    <li><a href="#" data-anchor="#contact">Contato</a></li>
                    <li><a href="<?= $this->url('auth/login') ?>">Entrar</a></li>
                    <?php if ($this->isLogged) { ?>
                </div>
            <?php } ?>
                <?php if ($this->isLogged) { ?>
                    <li><a href="<?= $this->url('accompaniment/my-account') ?>">Minha Conta</a></li>
                    <li><a href="<?= $this->url('auth/logout') ?>">Sair</a></li>
                <?php } ?>
            </ul>
        </div>
    </div>
</nav>